Bir dizinin dışına çıkıldığında assert() ile hatayı yakalayan bir örnek yaz.